//! Differential oracle against **rage**, the Rust implementation of age.
//!
//! The sibling of `tests/differential_age_go.rs`, pointed at a second
//! implementation. It runs the **same case matrix** — same seeds, same
//! plaintexts, generated by the same `common` helpers — so a disagreement is
//! attributable to the implementation rather than to the inputs, and "rage
//! agrees with us" and "age-go agrees with us" are comparable statements.
//!
//! | # | direction | what it proves |
//! |---|-----------|----------------|
//! | R1 | our identity → `rage-keygen -y` | rage's seed→recipient derivation agrees with [`HybridIdentity::to_public`] byte-for-byte, over 64 keys |
//! | R2 | `rage-keygen` → our parser | our decoders accept *arbitrary fresh* rage output, re-encode it identically, and derive the recipient rage printed |
//! | R3 | we encrypt → `rage -d` | our stanza is readable by rage |
//! | R4 | `rage -e` → we decrypt | rage's stanza and payload are readable by us |
//! | R5 | `rage -a -e` → we decrypt | the **armored** path, end to end and live |
//!
//! ## Why a second oracle is worth its cost
//!
//! Before this file, every cross-implementation claim in the repository rested
//! on one implementation: the Go `age` CLI. That is a strong oracle and it is
//! still not independent enough on its own — a specification ambiguity that
//! age-go and this crate happened to resolve the same way would be invisible,
//! and both would stay green forever.
//!
//! rage is a genuinely separate codebase: different language, different bignum
//! and bech32 stacks, different ML-KEM crate (RustCrypto `ml-kem`, where we use
//! the formally verified libcrux). A bug that is a function of the key bytes —
//! a carry, a leading-zero trim, a chunk boundary — has to survive all three to
//! stay hidden.
//!
//! It is *not*, on its own, evidence that we are right. Where all three agree
//! and the draft disagrees, the draft wins; that direction is covered by
//! `age-pq-hpke/tests/hpke_pq_draft_vectors.rs`, which checks published
//! known-answer vectors rather than another implementation's opinion.
//!
//! ## R5 closes a loop the testkit left open
//!
//! `tests/data/testkit/armor_hybrid` reached this repository *via* rage
//! (C2SP/CCTV `e9274a7b` → rage `26fe921` → here `85fe5c0`) and was
//! **decompressed** in transit, 1951 → 2554 bytes, to avoid a `flate2`
//! dependency. So the in-tree armored vector is a modified copy of rage's, and
//! nothing checked our armored path against rage's *live* output. R5 does.
//!
//! ## Locating the binary
//!
//! rage's post-quantum work lives on its `pq` branch, which has no tagged
//! release. There is no installer to point at the way `scripts/install-age.sh`
//! points at a pinned age tarball, so the binaries are found via `RAGE_BIN` /
//! `RAGE_KEYGEN_BIN` first and `PATH` second.
//!
//! **A version check cannot gate this.** Released rage 0.12.1 and the `pq`
//! branch answer `--version` identically, and only the branch implements
//! `mlkem768x25519` — the release carries `mlkem768p256tag`, a different
//! format. A version-only gate would let a released rage turn every
//! differential here into a no-op that still reports `ok`. So
//! `common::require_rage_pq_support` makes the binary *produce* a pq keypair
//! and asserts on the `age1pq` HRP before anything else runs.
//!
//! ## Secret handling
//!
//! Identical to the age-go oracle, and for the same reasons. Every case is
//! `SHA-256(committed domain ‖ index)`, so a failure is reproducible by index
//! and no key material needs printing. R2's keys come from rage's CSPRNG and
//! are the only genuinely secret ones here: they live in a [`Dynamic<String>`]
//! for their whole life, never touch disk, and failures report a truncated
//! digest handle of the **public** recipient instead.
//!
//! ## Anti-gutting
//!
//! [`rage_oracle_matrix_floors_hold`] is deliberately **not** `#[ignore]`d, so
//! it runs with no rage binary present and fails if the matrix is shrunk. The
//! shared generator it draws from is pinned by `GENERATOR_DIGEST` in
//! `differential_age_go.rs` — one digest for one matrix, checked in the file
//! that owns it. Each differential below prints an `R1:`…`R5:` banner only
//! after the binary has been spawned and proven pq-capable, so a banner is
//! positive evidence that real work ran.

#![forbid(unsafe_code)]

use age::Encryptor;
use age_pq_keys::{HybridIdentity, HybridRecipient};
use secure_gate::{ConstantTimeEq, Dynamic, RevealSecret};
use std::fs;
use std::io::{Read, Write};
use std::process::Stdio;

mod common;

use common::{PLAINTEXT_LENGTHS, identity_for_case, plaintext_for_case, public_handle, report};

/// Named once so every failure message says which implementation disagreed.
const ORACLE: &str = "rage (pq branch)";

/// The line terminator between identities on a child's stdin.
const NEWLINE: &[u8] = b"\n";

/// Cases in the derivation matrix (R1). One batched `rage-keygen -y` converts
/// all of them in a single process, so this is cheap.
const ORACLE_CASES: usize = 64;

/// Floor for [`ORACLE_CASES`].
const ORACLE_MIN_CASES: usize = 32;

/// Cases in each payload differential (R3, R4). Each costs a process spawn plus
/// up to 128 KiB of file I/O.
const ORACLE_STREAM_CASES: usize = 22;

/// Floor for [`ORACLE_STREAM_CASES`]: one full pass over `PLAINTEXT_LENGTHS`.
const ORACLE_MIN_STREAM_CASES: usize = PLAINTEXT_LENGTHS.len();

/// Keypairs drawn from rage's own CSPRNG for the decoder differential (R2).
const ORACLE_RAGE_KEYGEN_CASES: usize = 8;

/// Floor for [`ORACLE_RAGE_KEYGEN_CASES`].
///
/// Cannot be covered by a digest — rage's keys are random, so there is nothing
/// deterministic to hash, which is exactly why it needs an explicit floor. R2
/// is the only differential pointed at our **decoder** with fresh input, and
/// setting its count to 0 would make it pass vacuously with every other guard
/// still green: `report()` returns early on an empty failure list.
const ORACLE_MIN_RAGE_KEYGEN_CASES: usize = 4;

/// Cases in the armored differential (R5): one per plaintext length.
const ORACLE_ARMOR_CASES: usize = PLAINTEXT_LENGTHS.len();

// ---------------------------------------------------------------------------
// The anti-gutting guard — deliberately NOT #[ignore]d
// ---------------------------------------------------------------------------

/// Floors for every count in this file, with no rage binary needed.
///
/// The shared case *values* are pinned by `GENERATOR_DIGEST` in
/// `differential_age_go.rs`; this guards the counts that are local to this
/// oracle. Without it, setting `ORACLE_CASES` to 1 would leave the CI banner
/// checks green while reducing a 64-key differential to a single key.
// `clippy::assertions_on_constants` says a constant assertion is folded away and
// should be deleted. Its premise does not hold for a floor: the whole point is
// that these compare two constants, and that editing one of them downwards
// turns a green suite red.
#[allow(clippy::assertions_on_constants)]
#[test]
fn rage_oracle_matrix_floors_hold() {
    assert!(
        ORACLE_CASES >= ORACLE_MIN_CASES,
        "the rage derivation matrix was shrunk to {ORACLE_CASES}; floor is {ORACLE_MIN_CASES}"
    );
    assert!(
        ORACLE_STREAM_CASES >= ORACLE_MIN_STREAM_CASES,
        "the rage payload matrix was shrunk to {ORACLE_STREAM_CASES}; floor is \
         {ORACLE_MIN_STREAM_CASES} (one pass over PLAINTEXT_LENGTHS)"
    );
    assert!(
        ORACLE_RAGE_KEYGEN_CASES >= ORACLE_MIN_RAGE_KEYGEN_CASES,
        "the rage decoder matrix was shrunk to {ORACLE_RAGE_KEYGEN_CASES}; floor is \
         {ORACLE_MIN_RAGE_KEYGEN_CASES}"
    );
    assert!(
        ORACLE_ARMOR_CASES == PLAINTEXT_LENGTHS.len(),
        "R5 must cover every plaintext length"
    );

    // The matrix must be the *same* one the age-go oracle runs. If these two
    // ever diverged, the two oracles would be answering different questions
    // while appearing to answer the same one.
    assert_eq!(
        ORACLE_CASES, 64,
        "the shared derivation matrix is 64 cases in differential_age_go.rs"
    );
    assert_eq!(
        ORACLE_STREAM_CASES, 22,
        "the shared payload matrix is 22 cases in differential_age_go.rs"
    );
}

// ---------------------------------------------------------------------------
// R1 — our identity → rage-keygen -y
// ---------------------------------------------------------------------------

/// Converts every case's identity to a recipient in one `rage-keygen -y` spawn.
// (clippy::zombie_processes does not model `?` across a closure boundary — the
// same allow the age-go oracle carries on its equivalent.)
#[allow(clippy::zombie_processes)]
fn rage_recipients_for_all_cases() -> Vec<String> {
    let mut child = common::rage_keygen_command()
        .args(["-y"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        // Discarded rather than captured. age-keygen echoes the *entire* input
        // identity when it cannot parse one, and nothing guarantees rage is
        // more careful; a stderr that is never read cannot be printed later by
        // someone adding a diagnostic in good faith.
        .stderr(Stdio::null())
        .spawn()
        .expect("rage-keygen -y did not spawn");

    let mut stdin = child.stdin.take().expect("piped stdin");
    let writer = std::thread::spawn(move || -> std::io::Result<()> {
        for case in 0..ORACLE_CASES {
            let identity = identity_for_case(case);
            // Tier-2: `ChildStdin::write_all` takes `&[u8]`. `EncodedSecret`
            // has no `AsRef<[u8]>` on purpose, so this is the explicit hand-off.
            stdin.write_all(identity.as_bytes())?;
            stdin.write_all(b"\n")?;
        }
        stdin.flush()
    });

    let output = child
        .wait_with_output()
        .expect("rage-keygen -y did not run");

    // Join the writer first, for the reason spelled out in the age-go oracle: a
    // rejected identity makes rage exit early, the writer gets `BrokenPipe`, and
    // unwrapping it first would report plumbing trouble in exactly the scenario
    // the status assertion below exists for.
    let writer_result = writer.join().expect("the identity writer thread panicked");
    assert!(
        output.status.success(),
        "rage-keygen -y exited with {:?} (stderr withheld: it may echo the input identity)",
        output.status.code()
    );
    writer_result.expect("writing identities to rage-keygen failed");

    // `from_utf8_lossy`, never `String::from_utf8(..).expect(..)`: `expect`
    // formats the error with `{:?}`, which prints every input byte. Only public
    // recipients here, but R2's stdout would be a private key and the two paths
    // deliberately do not differ in habit.
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let lines: Vec<String> = stdout
        .lines()
        .map(|l| l.trim_end().to_owned())
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .collect();

    // Asserted before any comparison: a short read would otherwise silently
    // compare a prefix of the matrix and report success.
    assert!(
        lines.len() == ORACLE_CASES,
        "rage-keygen -y returned {} recipient(s) for {ORACLE_CASES} identities",
        lines.len()
    );
    lines
}

/// R1: rage's seed→recipient derivation agrees with ours, byte for byte.
#[test]
#[ignore = "requires a pq-branch rage; set RAGE_BIN/RAGE_KEYGEN_BIN and run with --include-ignored"]
fn rage_derives_the_same_recipient_from_our_identities() {
    let version = common::require_rage_cli();
    let keygen_version = common::require_rage_keygen_cli();
    common::require_rage_pq_support();
    eprintln!(
        "R1: derivation differential against {version} / {keygen_version}, {ORACLE_CASES} cases"
    );

    let theirs = rage_recipients_for_all_cases();
    let mut failures = vec![];

    for (case, rage_recipient) in theirs.iter().enumerate() {
        let ours = our_recipient_for_case(case);
        let ours_string = ours.to_string();

        // Compared without `assert_eq!` so a mismatch cannot dump two
        // 1959-character strings into the log.
        if &ours_string != rage_recipient {
            let attribution = match HybridRecipient::parse(rage_recipient) {
                Ok(parsed) if parsed.as_bytes() == ours.as_bytes() => {
                    "same key bytes, different encoding (encoder drift)"
                }
                Ok(_) => "different key bytes (derivation drift)",
                Err(_) => "rage's recipient does not parse at all",
            };
            failures.push(format!(
                "case {case}: recipient mismatch — {attribution} (ours {} chars, rage {} chars)",
                ours_string.len(),
                rage_recipient.len()
            ));
        }
    }

    report("R1 derivation", ORACLE, ORACLE_CASES, failures);
}

// ---------------------------------------------------------------------------
// R2 — rage-keygen → our parser
// ---------------------------------------------------------------------------

/// R2: our decoder round-trips *freshly generated* rage keypairs.
///
/// The only differential here whose inputs are not reproducible by index — the
/// keys come from rage's CSPRNG. It earns its place because it is the only
/// direction that points our **decoder** at arbitrary rage output.
#[test]
#[ignore = "requires a pq-branch rage; set RAGE_BIN/RAGE_KEYGEN_BIN and run with --include-ignored"]
fn we_reparse_freshly_generated_rage_keypairs() {
    let version = common::require_rage_cli();
    let keygen_version = common::require_rage_keygen_cli();
    common::require_rage_pq_support();
    eprintln!(
        "R2: decoder differential against {version} / {keygen_version}, \
         {ORACLE_RAGE_KEYGEN_CASES} cases"
    );

    let mut failures = vec![];

    for case in 0..ORACLE_RAGE_KEYGEN_CASES {
        let output = common::rage_keygen_command()
            .output()
            .expect("rage-keygen did not run");
        if !output.status.success() {
            failures.push(format!(
                "case {case}: rage-keygen exited with {:?}",
                output.status.code()
            ));
            continue;
        }

        // The whole keyfile is a secret: it carries the identity line. It stays
        // in a wrapper for its entire life and never reaches disk.
        let keyfile = Dynamic::<String>::new(String::from_utf8_lossy(&output.stdout).into_owned());

        let (identity_line, printed_recipient) = keyfile.with_secret(|text| {
            let identity = text
                .lines()
                .find(|l| !l.starts_with('#') && !l.trim().is_empty())
                .map(str::trim)
                .map(str::to_owned);
            let recipient = text
                .lines()
                .find_map(|l| l.strip_prefix("# public key: "))
                .map(str::trim)
                .map(str::to_owned);
            (identity, recipient)
        });

        let Some(identity_line) = identity_line else {
            failures.push(format!("case {case}: rage-keygen printed no identity line"));
            continue;
        };
        let Some(printed_recipient) = printed_recipient else {
            failures.push(format!(
                "case {case}: rage-keygen printed no `# public key:` comment"
            ));
            continue;
        };

        let identity_line = Dynamic::<String>::new(identity_line);

        // 1. Our parser accepts rage's identity.
        let parsed = match identity_line.with_secret(|s| HybridIdentity::parse(s)) {
            Ok(id) => id,
            Err(e) => {
                failures.push(format!(
                    "case {case}: our parser rejected a rage identity ({e}); recipient {}",
                    public_handle(&printed_recipient)
                ));
                continue;
            }
        };

        // 2. We derive the recipient rage printed.
        let ours = match parsed.to_public() {
            Ok(r) => r.to_string(),
            Err(e) => {
                failures.push(format!(
                    "case {case}: deriving a recipient from a rage identity failed ({e})"
                ));
                continue;
            }
        };
        if ours != printed_recipient {
            failures.push(format!(
                "case {case}: recipient mismatch on a rage-generated key — ours {}, rage {}",
                public_handle(&ours),
                public_handle(&printed_recipient)
            ));
            continue;
        }

        // 3. Our encoder reproduces rage's identity string exactly. This is the
        //    half that catches case or checksum drift, which step 2 cannot see:
        //    bech32 decoding is case-insensitive on the data part, so a
        //    lowercase identity would still parse and still derive correctly.
        // Both sides are private keys: wrapped, and compared with `ct_eq`.
        let ours_encoded = Dynamic::<String>::new(parsed.to_string());
        if !ours_encoded.ct_eq(&identity_line) {
            failures.push(format!(
                "case {case}: our re-encoding of a rage identity differs from rage's \
                 (contents withheld); recipient {}",
                public_handle(&printed_recipient)
            ));
        }
    }

    report("R2 decoder", ORACLE, ORACLE_RAGE_KEYGEN_CASES, failures);
}

// ---------------------------------------------------------------------------
// R3 — we encrypt → rage -d
// ---------------------------------------------------------------------------

/// R3: rage reads the stanza we produce.
#[test]
#[ignore = "requires a pq-branch rage; set RAGE_BIN/RAGE_KEYGEN_BIN and run with --include-ignored"]
fn rage_decrypts_what_we_encrypt() {
    let version = common::require_rage_cli();
    common::require_rage_pq_support();
    eprintln!("R3: our encrypt → rage decrypt against {version}, {ORACLE_STREAM_CASES} cases");

    let dir = tempfile::tempdir().expect("tempdir");
    let mut failures = vec![];

    for case in 0..ORACLE_STREAM_CASES {
        let plaintext = plaintext_for_case(case);
        let recipient = our_recipient_for_case(case);

        let ciphertext_path = dir.path().join(format!("r3-{case}.age"));
        let recovered_path = dir.path().join(format!("r3-{case}.out"));

        let mut ciphertext = Vec::new();
        {
            let encryptor =
                Encryptor::with_recipients(std::iter::once(&recipient as &dyn age::Recipient))
                    .expect("a validated recipient always builds an encryptor");
            let mut writer = encryptor
                .wrap_output(&mut ciphertext)
                .expect("wrapping an in-memory sink cannot fail");
            writer.write_all(&plaintext).expect("write plaintext");
            writer.finish().expect("finish");
        }
        fs::write(&ciphertext_path, &ciphertext).expect("write ciphertext");

        // `-i -` reads the identity from stdin so it never reaches disk, while
        // the ciphertext stays a file argument.
        let mut child = common::rage_command()
            .args([
                "-d".as_ref(),
                "-i".as_ref(),
                "-".as_ref(),
                "-o".as_ref(),
                recovered_path.as_os_str(),
                ciphertext_path.as_os_str(),
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("rage -d did not spawn");

        let mut stdin = child.stdin.take().expect("piped stdin");
        let identity = identity_for_case(case);
        // Tier-2: `ChildStdin::write_all` takes `&[u8]`; see R1's writer.
        let write_result = stdin
            .write_all(identity.as_bytes())
            .and_then(|()| stdin.write_all(NEWLINE));
        drop(stdin);
        let output = child.wait_with_output().expect("rage -d did not run");
        if let Err(e) = write_result {
            failures.push(format!(
                "case {case}: writing the identity to rage failed ({e})"
            ));
            continue;
        }

        if !output.status.success() {
            failures.push(format!(
                "case {case} ({} byte plaintext): rage -d exited with {:?}: {}",
                plaintext.len(),
                output.status.code(),
                common::safe_stderr(&output.stderr)
            ));
            continue;
        }

        // Reported, not `expect`ed: a panic here would discard every other
        // case's result, which is the whole reason this loop collects failures.
        //
        // The empty-plaintext exception is a measured CLI difference, not a
        // wire-format one, and it is narrowed to exactly the case that shows it:
        //
        //   rage -d -i F -o OUT ct   (0-byte payload)  exit 0, OUT not created
        //   rage -d -i F    ct       (0-byte payload)  exit 0, 0 bytes on stdout
        //   age  -d -i F -o OUT ct   (0-byte payload)  exit 0, OUT created, 0 B
        //
        // rage creates the output file lazily on first write, so a payload with
        // no bytes never triggers creation. Nothing about the stanza or the
        // payload framing differs — `status.success()` above already proves rage
        // unwrapped our stanza and ran the STREAM reader to completion, which
        // for an empty payload is the entire claim. A non-empty plaintext with
        // no output file stays a failure.
        let recovered = match fs::read(&recovered_path) {
            Ok(bytes) => bytes,
            Err(_) if plaintext.is_empty() => Vec::new(),
            Err(e) => {
                failures.push(format!(
                    "case {case} ({} byte plaintext): rage -d exited 0 but wrote no output file                      ({e}); stderr: {}",
                    plaintext.len(),
                    common::safe_stderr(&output.stderr)
                ));
                continue;
            }
        };
        if recovered != plaintext {
            failures.push(format!(
                "case {case}: rage decrypted {} bytes, expected {}",
                recovered.len(),
                plaintext.len()
            ));
        }
    }

    report(
        "R3 our encrypt → rage decrypt",
        ORACLE,
        ORACLE_STREAM_CASES,
        failures,
    );
}

// ---------------------------------------------------------------------------
// R4 — rage -e → we decrypt
// ---------------------------------------------------------------------------

/// R4: we read the stanza and payload rage produces.
#[test]
#[ignore = "requires a pq-branch rage; set RAGE_BIN/RAGE_KEYGEN_BIN and run with --include-ignored"]
fn we_decrypt_what_rage_encrypts() {
    let version = common::require_rage_cli();
    common::require_rage_pq_support();
    eprintln!("R4: rage encrypt → our decrypt against {version}, {ORACLE_STREAM_CASES} cases");

    let dir = tempfile::tempdir().expect("tempdir");
    let mut failures = vec![];

    for case in 0..ORACLE_STREAM_CASES {
        let plaintext = plaintext_for_case(case);
        let encoded_identity = identity_for_case(case);
        let identity =
            HybridIdentity::parse(&encoded_identity).expect("our own encoding must re-parse");
        let recipient = our_recipient_for_case(case).to_string();

        let plaintext_path = dir.path().join(format!("r4-{case}.bin"));
        let ciphertext_path = dir.path().join(format!("r4-{case}.age"));
        fs::write(&plaintext_path, &plaintext).expect("write plaintext");

        let output = common::rage_command()
            .args([
                "-e".as_ref(),
                "-r".as_ref(),
                recipient.as_ref(),
                "-o".as_ref(),
                ciphertext_path.as_os_str(),
                plaintext_path.as_os_str(),
            ])
            .output()
            .expect("rage -e did not run");

        if !output.status.success() {
            failures.push(format!(
                "case {case} ({} byte plaintext): rage -e exited with {:?}: {}",
                plaintext.len(),
                output.status.code(),
                common::safe_stderr(&output.stderr)
            ));
            continue;
        }

        let ciphertext = fs::read(&ciphertext_path).expect("read the ciphertext");
        match decrypt_with(&ciphertext, &identity) {
            Ok(recovered) if recovered == plaintext => {}
            Ok(recovered) => failures.push(format!(
                "case {case}: we decrypted {} bytes, expected {}",
                recovered.len(),
                plaintext.len()
            )),
            Err(e) => failures.push(format!("case {case}: {e}")),
        }
    }

    report(
        "R4 rage encrypt → our decrypt",
        ORACLE,
        ORACLE_STREAM_CASES,
        failures,
    );
}

// ---------------------------------------------------------------------------
// R5 — rage -a -e → we decrypt (armored)
// ---------------------------------------------------------------------------

/// R5: we read rage's **armored** output, live.
///
/// The in-tree `armor_hybrid` CCTV vector came from rage and was decompressed
/// in transit (1951 → 2554 bytes), so it is a modified copy rather than rage's
/// own bytes. This runs the real thing, at every plaintext length, including the
/// two that sit on age's 64 KiB STREAM chunk boundary — where armor's 64-column
/// line wrapping and the chunk framing interact.
#[test]
#[ignore = "requires a pq-branch rage; set RAGE_BIN/RAGE_KEYGEN_BIN and run with --include-ignored"]
fn we_decrypt_what_rage_armors() {
    let version = common::require_rage_cli();
    common::require_rage_pq_support();
    eprintln!(
        "R5: rage armored encrypt → our decrypt against {version}, {ORACLE_ARMOR_CASES} cases"
    );

    let dir = tempfile::tempdir().expect("tempdir");
    let mut failures = vec![];

    for case in 0..ORACLE_ARMOR_CASES {
        let plaintext = plaintext_for_case(case);
        let encoded_identity = identity_for_case(case);
        let identity =
            HybridIdentity::parse(&encoded_identity).expect("our own encoding must re-parse");
        let recipient = our_recipient_for_case(case).to_string();

        let plaintext_path = dir.path().join(format!("r5-{case}.bin"));
        let armored_path = dir.path().join(format!("r5-{case}.age"));
        fs::write(&plaintext_path, &plaintext).expect("write plaintext");

        let output = common::rage_command()
            .args([
                "-e".as_ref(),
                "-a".as_ref(),
                "-r".as_ref(),
                recipient.as_ref(),
                "-o".as_ref(),
                armored_path.as_os_str(),
                plaintext_path.as_os_str(),
            ])
            .output()
            .expect("rage -a -e did not run");

        if !output.status.success() {
            failures.push(format!(
                "case {case} ({} byte plaintext): rage -a -e exited with {:?}: {}",
                plaintext.len(),
                output.status.code(),
                common::safe_stderr(&output.stderr)
            ));
            continue;
        }

        let armored = fs::read(&armored_path).expect("read the armored ciphertext");

        // Asserted rather than assumed: if `-a` were ignored, this differential
        // would silently become a duplicate of R4 and still pass.
        if !armored.starts_with(b"-----BEGIN AGE ENCRYPTED FILE-----") {
            failures.push(format!(
                "case {case}: rage -a produced no armor header; R5 would duplicate R4"
            ));
            continue;
        }

        let reader = age::armor::ArmoredReader::new(&armored[..]);
        let decryptor = match age::Decryptor::new(reader) {
            Ok(d) => d,
            Err(e) => {
                failures.push(format!(
                    "case {case}: armored header from rage rejected ({e})"
                ));
                continue;
            }
        };
        let mut reader = match decryptor.decrypt(std::iter::once(&identity as &dyn age::Identity)) {
            Ok(r) => r,
            Err(e) => {
                failures.push(format!(
                    "case {case}: our identity did not unwrap rage's armored stanza ({e})"
                ));
                continue;
            }
        };
        let mut recovered = Vec::new();
        if let Err(e) = reader.read_to_end(&mut recovered) {
            failures.push(format!(
                "case {case} ({} byte plaintext): armored payload read failed ({e})",
                plaintext.len()
            ));
            continue;
        }
        if recovered != plaintext {
            failures.push(format!(
                "case {case}: we decrypted {} armored bytes, expected {}",
                recovered.len(),
                plaintext.len()
            ));
        }
    }

    report(
        "R5 rage armored encrypt → our decrypt",
        ORACLE,
        ORACLE_ARMOR_CASES,
        failures,
    );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// The public recipient our implementation derives for a case.
fn our_recipient_for_case(case: usize) -> HybridRecipient {
    let identity = identity_for_case(case);
    HybridIdentity::parse(&identity)
        .unwrap_or_else(|_| panic!("case {case}: our own identity encoding must re-parse"))
        .to_public()
        .unwrap_or_else(|_| panic!("case {case}: deriving the recipient must succeed"))
}

/// Decrypts binary age ciphertext with one identity, flattening the several
/// failure points into one message so callers stay readable.
fn decrypt_with(ciphertext: &[u8], identity: &HybridIdentity) -> Result<Vec<u8>, String> {
    let decryptor =
        age::Decryptor::new(ciphertext).map_err(|e| format!("header from rage rejected ({e})"))?;
    let mut reader = decryptor
        .decrypt(std::iter::once(identity as &dyn age::Identity))
        .map_err(|e| format!("our identity did not unwrap rage's stanza ({e})"))?;
    let mut recovered = Vec::new();
    reader
        .read_to_end(&mut recovered)
        .map_err(|e| format!("payload read failed ({e})"))?;
    Ok(recovered)
}
