use crate::SharedSecret;
use sha3::{Digest, Sha3_256};

pub(crate) const X_WING_LABEL: &[u8] = br"\.//^\";

/// Combines the PQ and traditional shared secrets into a single shared secret using SHA3-256.
/// This follows hpke-pq.md (draft-ietf-hpke-pq-03) for hybrid KEM derivation.
/// Inputs: PQ shared secret (ss_pq), traditional ECDH shared secret (ss_t), traditional encapsulation (ct_t), and traditional public key (pk_t).
/// The domain separator label is appended to ensure uniqueness and prevent cross-protocol attacks.
pub fn combine_shared_secrets(
    // ss_pq: Shared secret from ML-KEM (post-quantum KEM). This is the output of ML-KEM decapsulation (for recipient) or encapsulation (for sender), a 32-byte symmetric key derived from lattice-based cryptography. It provides the main post-quantum security for the hybrid scheme.
    ss_pq: &[u8; 32],
    // ss_t: Shared secret from traditional ECDH (e.g., X25519). This is the result of the ephemeral-static DH computation (ephemeral_key * static_public_key), a 32-byte value that adds classical ECDH security to mitigate ML-KEM weaknesses.
    ss_t: &[u8; 32],
    // ct_t: Traditional ECDH encapsulation. This is the ephemeral public key generated by the sender during encapsulation (a 32-byte Curve25519 point). The recipient uses this to compute ss_t via Diffie-Hellman.
    ct_t: &[u8; 32],
    // ek_t: Recipient's static traditional encapsulation key. This is the long-term public key of the recipient (a 32-byte Curve25519 point). It's used to compute ss_t and ensures the DH exchange is bound to the correct recipient.
    ek_t: &[u8; 32],
) -> SharedSecret {
    SharedSecret::new_with(|buf| {
        let mut hasher = Sha3_256::new();
        hasher.update(ss_pq);
        hasher.update(ss_t);
        hasher.update(ct_t);
        hasher.update(ek_t);
        hasher.update(X_WING_LABEL);
        buf.copy_from_slice(&hasher.finalize());
    })
}
